export const supportedLanguages = [
    { id: 1, name: 'apex' },
    { id: 2, name: 'azcli' },
    { id: 3, name: 'bat' },
    { id: 4, name: 'c' },
    { id: 5, name: 'clojure' },
    { id: 6, name: 'coffeescript' },
    { id: 7, name: 'cpp' },
    { id: 8, name: 'csharp' },
    { id: 9, name: 'csp' },
    { id: 10, name: 'css' },
    { id: 11, name: 'dockerfile' },
    { id: 12, name: 'fsharp' },
    { id: 13, name: 'go' },
    { id: 14, name: 'graphql' },
    { id: 15, name: 'handlebars' },
    { id: 16, name: 'html' },
    { id: 17, name: 'ini' },
    { id: 18, name: 'java' },
    { id: 19, name: 'javascript' },
    { id: 20, name: 'json' },
    { id: 21, name: 'kotlin' },
    { id: 22, name: 'less' },
    { id: 23, name: 'lua' },
    { id: 24, name: 'markdown' },
    { id: 25, name: 'msdax' },
    { id: 26, name: 'mysql' },
    { id: 27, name: 'objective-c' },
    { id: 28, name: 'pascal' },
    { id: 29, name: 'perl' },
    { id: 30, name: 'pgsql' },
    { id: 31, name: 'php' },
    { id: 32, name: 'plaintext' },
    { id: 33, name: 'postiats' },
    { id: 34, name: 'powerquery' },
    { id: 35, name: 'powershell' },
    { id: 36, name: 'pug' },
    { id: 37, name: 'python' },
    { id: 38, name: 'r' },
    { id: 39, name: 'razor' },
    { id: 40, name: 'redis' },
    { id: 41, name: 'redshift' },
    { id: 42, name: 'ruby' },
    { id: 43, name: 'rust' },
    { id: 44, name: 'sb' },
    { id: 45, name: 'scheme' },
    { id: 46, name: 'scss' },
    { id: 47, name: 'shell' },
    { id: 48, name: 'sol' },
    { id: 49, name: 'sql' },
    { id: 50, name: 'st' },
    { id: 51, name: 'swift' },
    { id: 52, name: 'tcl' },
    { id: 53, name: 'typescript' },
    { id: 54, name: 'vb' },
    { id: 55, name: 'xml' },
    { id: 56, name: 'yaml' }
]


export const supportedThemes = [
    { id: 'vs-dark', name: 'Vs Dark' },
    { id: 'light', name: 'Light' },
    { id: 'active4d', name: 'Active4D' },
    // { id: 'all-hallows-eve', name: 'All Hallows Eve' },
    { id: 'amy', name: 'Amy' },
    // { id: 'birds-of-paradise', name: 'Birds of Paradise' },
    { id: 'blackboard', name: 'Blackboard' },
    // { id: 'brilliance-black', name: 'Brilliance Black' },
    // { id: 'brilliance-dull', name: 'Brilliance Dull' },
    // { id: 'chrome-devtools', name: 'Chrome DevTools' },
    // { id: 'clouds-midnight', name: 'Clouds Midnight' },
    { id: 'clouds', name: 'Clouds' },
    { id: 'cobalt', name: 'Cobalt' },
    { id: 'cobalt2', name: 'Cobalt2' },
    { id: 'dawn', name: 'Dawn' },
    { id: 'dracula', name: 'Dracula' },
    { id: 'dreamweaver', name: 'Dreamweaver' },
    { id: 'eiffel', name: 'Eiffel' },
    // { id: 'espresso-libre', name: 'Espresso Libre' },
    // { id: 'github-dark', name: 'GitHub Dark' },
    // { id: 'github-light', name: 'GitHub Light' },
    { id: 'github', name: 'GitHub' },
    { id: 'idle', name: 'IDLE' },
    { id: 'katzenmilch', name: 'Katzenmilch' },
    // { id: 'kuroir-theme', name: 'Kuroir Theme' },
    { id: 'lazy', name: 'LAZY' },
    // { id: 'magicwb--amiga-', name: 'MagicWB (Amiga)' },
    // { id: 'merbivore-soft', name: 'Merbivore Soft' },
    { id: 'merbivore', name: 'Merbivore' },
    // { id: 'monokai-bright', name: 'Monokai Bright' },
    { id: 'monokai', name: 'Monokai' },
    // { id: 'night-owl', name: 'Night Owl' },
    { id: 'nord', name: 'Nord' },
    // { id: 'oceanic-next', name: 'Oceanic Next' },
    // { id: 'pastels-on-dark', name: 'Pastels on Dark' },
    // { id: 'slush-and-poppies', name: 'Slush and Poppies' },
    { id: 'solarized-dark', name: 'Solarized-dark' },
    { id: 'solarized-light', name: 'Solarized-light' },
    { id: 'spacecadet', name: 'SpaceCadet' },
    { id: 'sunburst', name: 'Sunburst' },
    // { id: 'textmate--mac-classic-', name: 'Textmate (Mac Classic)' },
    { id: 'tomorrow-night-blue', name: 'Tomorrow-Night-Blue' },
    { id: 'tomorrow-night-bright', name: 'Tomorrow-Night-Bright' },
    { id: 'tomorrow-night-eighties', name: 'Tomorrow-Night-Eighties' },
    { id: 'tomorrow-night', name: 'Tomorrow-Night' },
    { id: 'tomorrow', name: 'Tomorrow' },
    { id: 'twilight', name: 'Twilight' },
    // { id: 'upstream-sunburst', name: 'Upstream Sunburst' },
    // { id: 'vibrant-ink', name: 'Vibrant Ink' },
    // { id: 'xcode-default', name: 'Xcode_default' },
    { id: 'zenburnesque', name: 'Zenburnesque' },
    { id: 'iplastic', name: 'iPlastic' },
    { id: 'idlefingers', name: 'idleFingers' },
    { id: 'krtheme', name: 'krTheme' },
    { id: 'monoindustrial', name: 'monoindustrial' }
]